### ISSUE TITLE
Differents

### ISSUE THREAD

**Issue by Rus3545** [CMuncey/OoT_Compressor#4]
It's not a issue. Just a question.
There is Zoinkity's Aegh rom compressor: [Link](https://hylianmodding.com/Thread-Tools-for-decompressing-retail-roms-recompressing-any-Zelda-rom-and-correcting-CRC)
Significant differences?

**Comment by CMuncey** [comment]
This one is much faster.

**Comment by Rus3545** [comment]
Thanks.
